---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Peter Draw"
keywords:    "peter draw blog"
description: "Peter Draw's blog."
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: "" ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
### trove - http://colrd.com/palette/19308/
colors:
  color_primary_1: '#ffeebb'
  color_primary_2: '#ffb051'
  color_primary_3: '#a54c3e'
  color_primary_4: '#5b664b'
  color_primary_5: '#88aa99'
  color_primary_6: '#bc7138'
  color_primary_7: '#805732'

  color_1:	'#51574a'
  color_2:	'#447c69'
  color_3:	'#74c493'
  color_4:	'#8e8c6d'
  color_5:	'#e4bf80'
  color_6:	'#e9d78e'
  color_7:	'#e2975d'
  color_8:	'#f19670'
  color_9:	'#e16552'
  color_10:	'#c94a53'
  color_11:	'#be5168'
  color_12:	'#a34974'
  color_13:	'#993767'
  color_14:	'#65387d'
  color_15:	'#9163b6'
  color_16:	'#4e2472'
  color_17:	'#e279a3'
  color_18:	'#e0598b'
  color_19:	'#7c9fb0'
  color_20:	'#5698c4'
  color_21:	'#9abf88'

### jekyll-minimagick, auto generate thumbnails ###
mini_magick:
  thumbnail:
    source: img/
    destination: img/thumbnail
    resize: "300x300"
